[package]
name = "rusty-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
crossterm = "0.28.1"
streaming-iterator = "0.1.9"
tree-sitter = "0.24.4"
tree-sitter-rust = "0.23.2"
